title:             2381 Robotics
email:             sdammobubbles@gmail.com
description:       2381 Robotics
author:            Sean D'Souza
baseurl:           "/2381-Robotics"
url:               "http://seendsouza.github.io"

# Social Profiles
gitlab_username:  2381-Robotics
github_username:   andydabin
instagram_username: 2381_kernel_bye

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - github-pages

# Github Pages
lsi: false
safe: true
#source: "https://github.com/seendsouza/2381-Robotics"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Other
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
